// <auto-generated />
namespace Homiee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HotelInfoesdatabasecreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HotelInfoesdatabasecreated));
        
        string IMigrationMetadata.Id
        {
            get { return "202110012057379_HotelInfoes-database-created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
